version: '2'

services:
  
  teamRocket:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: teamRocket
    container_name: teamRocket
    networks:
      x1:
        ipv4_address: 192.168.10.2
    
  maquina1:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: teamRocket
    container_name: teamRocket
    networks:
      x1:
        ipv4_address: 192.168.10.29
        
  maquina2:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: teamRocket
    container_name: teamRocket
    networks:
      x1:
        ipv4_address: 192.168.10.11
        

  maquina3:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: teamRocket
    container_name: teamRocket
    networks:
      x1:
        ipv4_address: 192.168.10.148

networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.0/24
          gateway: 192.168.10.1
          aux_addresses:
            host1: 192.168.10.2
            host2: 192.168.10.29
            host3: 192.168.10.11
            host4: 192.168.10.148
