version: '2'

services:
  
  teamRocket:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: teamRocket
    container_name: teamRocket
    networks:
      x1:
        ipv4_address: 192.168.10.2
    
  maquina1:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: maquina1
    container_name: maquina1
    networks:
      x1:
        ipv4_address: 192.168.10.29
        
  maquina2:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: maquina2
    container_name: maquina2
    networks:
      x1:
        ipv4_address: 192.168.10.11
        

  maquina3:
    image: ubuntu
    privileged: true
    mem_limit: 100m
    hostname: maquina3
    container_name: maquina3
    networks:
      x1:
        ipv4_address: 192.168.10.148

networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.0/24
          gateway: 192.168.10.1
